In [1]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
import matplotlib as mpl

Exercise 2: Will the following code block work?  

In [14]:
# This creates a 3x3 array of random numbers ranging from 0 to 1
array1 = np.random.random((3, 3))
array2 = np.random.random((3, 1))

np.add(array1,array2)

# Array shape is the same so they can be added

array([[0.61768595, 0.34052487, 0.8321084 ],
       [1.06666651, 0.54503846, 0.54034664],
       [1.03674002, 0.83775904, 0.57473545]])

Exercise 3: What about now?

In [13]:
# This creates a 3x3 array of random numbers ranging from 0 to 1
array3 = np.random.random((3, 3))
array4 = np.random.random((3, 2))

np.add(array3,array4)

# Array shape is not the same so they cannot be added. I don't understand it from the code, though. Is the shape in 3, 3 and 3,1 for arrays 1 and 2 and 3, 3 and 3,2 for arrays 3 and 4? 

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

Exercise 4: by inspecting the arrays 1 to 4 can you figure out why one operation worked and another one didn't? (hint: check their values and shape)

In [12]:
print (array1)
print (array2)
print (array3)
print (array4)

#I think it's the sum of some of them that is out the range 0 to 1 that is defined at the start.


[[0.69379117 0.48606754 0.26808442]
 [0.64603718 0.00101522 0.21086198]
 [0.74725148 0.79067784 0.08075496]]
[[0.26061319]
 [0.48316826]
 [0.60746479]]
[[0.27961085 0.60668114 0.01995731]
 [0.52891316 0.06528528 0.76447752]
 [0.85864974 0.12008888 0.30129681]]
[[0.12403885 0.7259241 ]
 [0.39885504 0.99824369]
 [0.36181576 0.81185543]]


Exercise 5: Using the function to create an array of random numbers [np.random.random](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html) how can you modify the code (as in the cells above) so that the numbers will vary between 0 and 100 instead of 0 and 1? And how can you modify the shape of the function?

In [21]:
array5 = np.random.uniform(0,100,(5,6))

Exercise 6: Using the array defined on the exercise above, use [np.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html) to find the positions the values that are larger than 50 (or feel free to pick any other number).

In [26]:
np.where(array5>50)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4],
       dtype=int64),
 array([0, 1, 2, 4, 0, 2, 3, 4, 5, 0, 1, 2, 1, 4, 5, 0, 1, 2, 3, 5],
       dtype=int64))

<h1>Pandas </h1>
There are two datasets on available to this work one is the pokemon dataset we explored in the lectured and the other one is the same dataframe but, for the sake of a nice story, let us say it was sabotaged by team rocket.

Exercise 1: open both dataframes supplied using [pd.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) (and don't forget to assign them to different objects).

In [5]:
sabotagepokemon = pd.read_csv("Pokemon_sabotage.csv")
goodpokemon = pd.read_csv("Pokemon.csv")

In [23]:
goodpokemon

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

Exercise 2: Using [pd.isna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html) check how many missing numbers are in each dataframe.

In [11]:
goodpokemon[goodpokemon.isna() is True]

KeyError: False

In [13]:
goodpokemon.isna()

#   Name  Type 1  Type 2  Total     HP  Attack  Defense  Sp. Atk  \
0    False  False   False   False  False  False   False    False    False   
1    False  False   False   False  False  False   False    False    False   
2    False  False   False   False  False  False   False    False    False   
3    False  False   False   False  False  False   False    False    False   
4    False  False   False    True  False  False   False    False    False   
..     ...    ...     ...     ...    ...    ...     ...      ...      ...   
795  False  False   False   False  False  False   False    False    False   
796  False  False   False   False  False  False   False    False    False   
797  False  False   False   False  False  False   False    False    False   
798  False  False   False   False  False  False   False    False    False   
799  False  False   False   False  False  False   False    False    False   

     Sp. Def  Speed  Generation  Legendary  
0      False  False       False      False  
1      False  False       False      False  
2      False  False       False      False  
3      False  False       False      False  
4      False  False       False      False  
..       ...    ...         ...        ...  
795    False  False       False      False  
796    False  False       False      False  
797    False  False       False      False  
798    False  False       False      False  
799    False  False       False      False  

[800 rows x 13 columns]

In [12]:
goodpokemon.isna().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [14]:
sabotagepokemon.isna().sum()

Unnamed: 0      0
Name            2
Type 1          1
Type 2        387
Total           0
HP              3
Attack          0
Defense         1
Sp. Atk         0
Sp. Def         1
Speed           4
Generation      0
Legendary       0
dtype: int64

In [6]:
pd.isna(goodpokemon)
pd.isna(sabotagepokemon)
#I don't know how to count the missing numbers in each dataframe

Unnamed: 0   Name  Type 1  Type 2  Total     HP  Attack  Defense  \
0         False  False   False   False  False  False   False    False   
1         False  False   False   False  False  False   False    False   
2         False  False   False   False  False  False   False    False   
3         False  False   False   False  False  False   False    False   
4         False  False   False    True  False  False   False    False   
..          ...    ...     ...     ...    ...    ...     ...      ...   
795       False  False   False   False  False  False   False    False   
796       False  False   False   False  False  False   False    False   
797       False  False   False   False  False  False   False    False   
798       False  False   False   False  False  False   False    False   
799       False  False   False   False  False  False   False    False   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0      False    False  False       False      False  
1      False    False  False       False      False  
2      False    False  False       False      False  
3      False    False  False       False      False  
4      False    False  False       False      False  
..       ...      ...    ...         ...        ...  
795    False    False  False       False      False  
796    False    False  False       False      False  
797    False    False  False       False      False  
798    False    False  False       False      False  
799    False    False  False       False      False  

[800 rows x 13 columns]

Exercise 3: Two of the main ways to deal with missing data is [pd.dropna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html) and [pd.fillna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html). How are these methods different from each other in how they deal with the missing data? Which, if any, would you use on the dataset? Why?

In [ ]:
#fillna fills NA/NaN values using specified methods
#dropna NA/NaN values are removed
#I would use fillna so that they become defined.

From now on we will only be working with the main (non sabotaged dataframe).<br>

Exercise 4: to free up memory delete the sabotaged dataframe. Bonus: before deleting find a way to check how much space in memory the dataframes occupy. [hint](https://stackoverflow.com/questions/449560/how-do-i-determine-the-size-of-an-object-in-python)

In [15]:
sys.getsizeof(sabotagepokemon)

199279

In [17]:
del sabotagepokemon

Exercise 5: Create a new column that contains the sum of the Attack, speed and defense stats.

In [24]:
goodpokemon['Atk+spd+defense'] = goodpokemon['Attack']+goodpokemon['Speed']+goodpokemon['Defense']

print (goodpokemon['Atk+spd+defense'])

0      143
1      185
2      245
3      303
4      160
      ... 
795    300
796    380
797    240
798    300
799    300
Name: Atk+spd+defense, Length: 800, dtype: int64


In [20]:
#This is copied from internet, but it's for me to remember that we don't need to over complicate 
goodpokemon_new = goodpokemon.groupby(['Attack', 'Speed', 'Defense']).apply(lambda x : x.astype(float).sum())

ValueError: could not convert string to float: 'Happiny'

Exercise 6: Find out the mean value of the attack, speed, defense columns and the new column that was created above.

In [21]:
goodpokemon.mean('Attack')

ValueError: No axis named Attack for object type DataFrame

Exercise 7: Find out how many pokemon have above average stats in the attack, speed, defense and the new column. Bonus: Do the pokemon with above average stats have a preffered type?

Super bonus: There are many platforms out there that contain different tools to boost your learning. Then for the super bonus create an account on [kaggle](https://www.kaggle.com/) and complete the courses
[intro to programming](https://www.kaggle.com/learn/intro-to-programming) and [intro to python](https://www.kaggle.com/learn/python) courses. All kaggle courses are free of charge and offer a [certificate](https://www.kaggle.com/learn-course-certificates) !